from __future__ import annotations

import argparse
import base64
import binascii
import hashlib
import json
import re
import tomllib
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse


SEMVER_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
UPDATER_ENDPOINT = "https://github.com/Speeson/weeklyChar/releases/latest/download/latest.json"
RELEASE_DOWNLOAD_BASE = "https://github.com/Speeson/weeklyChar/releases/download"
MANUAL_INSTALLER_NAME = "KeystoneClientSetup.exe"


class ReleaseError(ValueError):
    pass


def _require_version(version: str) -> str:
    version = version.strip()
    if not SEMVER_RE.fullmatch(version):
        raise ReleaseError(f"Invalid semantic version: {version!r}")
    return version


def _paths(root: Path) -> dict[str, Path]:
    client = root / "keystone-client"
    return {
        "VERSION": root / "keystone-client" / "VERSION",
        "package.json": client / "package.json",
        "package-lock.json": client / "package-lock.json",
        "Cargo.toml": client / "src-tauri" / "Cargo.toml",
        "tauri.conf.json": client / "src-tauri" / "tauri.conf.json",
    }


def read_versions(root: Path) -> dict[str, str]:
    paths = _paths(root)
    try:
        package = json.loads(paths["package.json"].read_text(encoding="utf-8"))
        package_lock = json.loads(paths["package-lock.json"].read_text(encoding="utf-8"))
        tauri = json.loads(paths["tauri.conf.json"].read_text(encoding="utf-8"))
        with paths["Cargo.toml"].open("rb") as handle:
            cargo = tomllib.load(handle)
        versions = {
            "VERSION": paths["VERSION"].read_text(encoding="utf-8-sig").strip(),
            "package.json": str(package["version"]),
            "package-lock.json": str(package_lock["packages"][""]["version"]),
            "Cargo.toml": str(cargo["package"]["version"]),
            "tauri.conf.json": str(tauri["version"]),
        }
    except (OSError, KeyError, json.JSONDecodeError, tomllib.TOMLDecodeError) as exc:
        raise ReleaseError(f"Could not read Tauri release versions: {exc}") from exc

    for source, version in versions.items():
        try:
            _require_version(version)
        except ReleaseError as exc:
            raise ReleaseError(f"{source}: {exc}") from exc
    return versions


def validate_versions(root: Path, expected: str | None = None) -> str:
    versions = read_versions(root)
    canonical = _require_version(expected) if expected else versions["VERSION"]
    drift = [f"{source}={version}" for source, version in versions.items() if version != canonical]
    if drift:
        raise ReleaseError(f"Tauri version drift from {canonical}: {', '.join(drift)}")
    return canonical


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _update_cargo_package_version(text: str, version: str) -> str:
    package_match = re.search(r"(?ms)^\[package\]\s*$.*?(?=^\[|\Z)", text)
    if not package_match:
        raise ReleaseError("Cargo.toml is missing [package]")
    package = package_match.group(0)
    updated, count = re.subn(
        r'(?m)^(version[ \t]*=[ \t]*)"[^"]+"[ \t]*$',
        lambda match: f'{match.group(1)}"{version}"',
        package,
        count=1,
    )
    if count != 1:
        raise ReleaseError("Cargo.toml [package] must contain exactly one version")
    return text[: package_match.start()] + updated + text[package_match.end() :]


def sync_versions(root: Path, version: str, notes: str) -> None:
    version = _require_version(version)
    paths = _paths(root)

    package = json.loads(paths["package.json"].read_text(encoding="utf-8"))
    package["version"] = version
    _write_json(paths["package.json"], package)

    package_lock = json.loads(paths["package-lock.json"].read_text(encoding="utf-8"))
    package_lock["version"] = version
    package_lock["packages"][""]["version"] = version
    _write_json(paths["package-lock.json"], package_lock)

    tauri = json.loads(paths["tauri.conf.json"].read_text(encoding="utf-8"))
    tauri["version"] = version
    _write_json(paths["tauri.conf.json"], tauri)

    cargo_text = paths["Cargo.toml"].read_text(encoding="utf-8")
    paths["Cargo.toml"].write_text(
        _update_cargo_package_version(cargo_text, version), encoding="utf-8"
    )
    paths["VERSION"].write_text(f"{version}\n", encoding="utf-8")

    generated = root / "keystone-client" / "src" / "generated" / "release.ts"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(
        "// Generated by scripts/tauri_release.py.\n"
        "export const bundledRelease = {\n"
        f"  version: {json.dumps(version)},\n"
        f"  notes: {json.dumps(notes.strip(), ensure_ascii=False)},\n"
        "} as const;\n",
        encoding="utf-8",
    )

    validate_versions(root, expected=version)


def read_updater_public_key(root: Path) -> str:
    config_path = _paths(root)["tauri.conf.json"]
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
        public_key = str(config["plugins"]["updater"]["pubkey"]).strip()
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        raise ReleaseError(f"Could not read the Tauri updater public key: {exc}") from exc

    if not public_key or "PLACEHOLDER" in public_key.upper() or "LOCAL_BUILD_ONLY" in public_key.upper():
        raise ReleaseError("The Tauri updater public key is missing or is a placeholder")
    try:
        decoded = base64.b64decode(public_key, validate=True).decode("utf-8")
        lines = decoded.splitlines()
        key_bytes = base64.b64decode(lines[1], validate=True)
    except (binascii.Error, UnicodeDecodeError, IndexError) as exc:
        raise ReleaseError("The Tauri updater public key has an invalid format") from exc
    if not lines[0].startswith("untrusted comment: minisign public key:") or len(key_bytes) != 42:
        raise ReleaseError("The Tauri updater public key has an invalid format")
    return public_key


def write_release_config(root: Path, version: str, output: Path) -> None:
    version = _require_version(version)
    read_updater_public_key(root)

    _write_json(
        output,
        {
            "version": version,
            "bundle": {"targets": ["nsis"], "createUpdaterArtifacts": True},
        },
    )


def _validate_rfc3339(value: str) -> None:
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ReleaseError(f"Invalid RFC 3339 publication date: {value}") from exc


def write_update_manifest(
    *,
    version: str,
    notes: str,
    pub_date: str,
    installer_url: str,
    signature_file: Path,
    output: Path,
) -> None:
    version = _require_version(version)
    _validate_rfc3339(pub_date)
    parsed = urlparse(installer_url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise ReleaseError("Updater installer URL must use HTTPS")
    if any(character.isspace() for character in installer_url):
        raise ReleaseError("Updater installer URL must be URL-encoded")
    try:
        signature = signature_file.read_text(encoding="utf-8").strip()
    except OSError as exc:
        raise ReleaseError(f"Could not read updater signature: {exc}") from exc
    if not signature:
        raise ReleaseError("Updater signature is empty")

    _write_json(
        output,
        {
            "version": version,
            "notes": notes.strip(),
            "pub_date": pub_date,
            "platforms": {
                "windows-x86_64": {"signature": signature, "url": installer_url}
            },
        },
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_release_artifacts(
    *,
    root: Path,
    expected_version: str,
    source_installer: Path,
    installer: Path,
    signature_file: Path,
    manifest_file: Path,
) -> None:
    expected_version = validate_versions(root, expected=expected_version)
    expected_source_name = f"KeystoneClient_{expected_version}_x64-setup.exe"
    if source_installer.name != expected_source_name:
        raise ReleaseError(f"Tauri source installer must be named {expected_source_name}")
    if installer.name != MANUAL_INSTALLER_NAME:
        raise ReleaseError(f"Manual installer must be named {MANUAL_INSTALLER_NAME}")
    if signature_file.name != f"{MANUAL_INSTALLER_NAME}.sig":
        raise ReleaseError(f"Updater signature must be named {MANUAL_INSTALLER_NAME}.sig")
    if manifest_file.name != "latest.json":
        raise ReleaseError("Updater manifest must be named latest.json")

    try:
        if _sha256(source_installer) != _sha256(installer):
            raise ReleaseError("Staged installer bytes do not match the signed source installer bytes")
        signature = signature_file.read_text(encoding="utf-8").strip()
        manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
        windows = manifest["platforms"]["windows-x86_64"]
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        raise ReleaseError(f"Could not validate updater release artifacts: {exc}") from exc

    if manifest.get("version") != expected_version:
        raise ReleaseError("Updater manifest version does not match the build version")
    expected_url = (
        f"{RELEASE_DOWNLOAD_BASE}/client-v{expected_version}/{MANUAL_INSTALLER_NAME}"
    )
    if windows.get("url") != expected_url:
        raise ReleaseError("Updater manifest URL does not match the release asset")
    if not signature or windows.get("signature") != signature:
        raise ReleaseError("Updater manifest signature does not match the signature asset")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Prepare and validate KeystoneClient Tauri releases.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    commands = parser.add_subparsers(dest="command", required=True)

    validate = commands.add_parser("validate-versions")
    validate.add_argument("--expected")

    sync = commands.add_parser("sync-versions")
    sync.add_argument("--version", required=True)
    sync.add_argument("--notes-file", type=Path, required=True)

    config = commands.add_parser("write-release-config")
    config.add_argument("--version", required=True)
    config.add_argument("--output", type=Path, required=True)

    manifest = commands.add_parser("write-manifest")
    manifest.add_argument("--version", required=True)
    manifest.add_argument("--notes-file", type=Path, required=True)
    manifest.add_argument("--pub-date", required=True)
    manifest.add_argument("--installer-url", required=True)
    manifest.add_argument("--signature-file", type=Path, required=True)
    manifest.add_argument("--output", type=Path, required=True)

    preflight = commands.add_parser("preflight-release")
    preflight.add_argument("--expected-version", required=True)
    preflight.add_argument("--source-installer", type=Path, required=True)
    preflight.add_argument("--installer", type=Path, required=True)
    preflight.add_argument("--signature-file", type=Path, required=True)
    preflight.add_argument("--manifest-file", type=Path, required=True)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "validate-versions":
            print(validate_versions(args.root, args.expected))
        elif args.command == "sync-versions":
            sync_versions(
                args.root,
                args.version,
                args.notes_file.read_text(encoding="utf-8-sig"),
            )
        elif args.command == "write-release-config":
            write_release_config(args.root, args.version, args.output)
        elif args.command == "write-manifest":
            write_update_manifest(
                version=args.version,
                notes=args.notes_file.read_text(encoding="utf-8-sig"),
                pub_date=args.pub_date,
                installer_url=args.installer_url,
                signature_file=args.signature_file,
                output=args.output,
            )
        elif args.command == "preflight-release":
            validate_release_artifacts(
                root=args.root,
                expected_version=args.expected_version,
                source_installer=args.source_installer,
                installer=args.installer,
                signature_file=args.signature_file,
                manifest_file=args.manifest_file,
            )
    except (OSError, json.JSONDecodeError, ReleaseError) as exc:
        parser = _parser()
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
