// Generated by tools/planner-ranking-data/generate.mjs. Do not edit by hand.
export const PLANNER_RANKING_DATA = {
  "version": "midnight-s2-v1",
  "sourceSha256": "8491a93b857abca077267eff96c18273b7038e6432f3ac212bf4aa270a216cc6",
  "source": {
    "buffDataset": "keystone-planner-buff-sims-poc:1:SimulationCraft 1210-01 for World of Warcraft 12.1.0.69587 Live (hotfix 2026-09-04/69587, git build midnight c1935b9)",
    "utilityCatalog": "keystone-planner-midnight-s2-utility-v1",
    "mechanicsDataset": "midnight-s2-dungeon-mechanics-v1",
    "dungeonRelevanceDataset": "midnight-s2-dungeon-utility-relevance-v1"
  },
  "offensiveBuffs": [
    "MARK_OF_THE_WILD",
    "BATTLE_SHOUT",
    "ARCANE_INTELLECT",
    "SKYFURY",
    "CHAOS_BRAND",
    "MYSTIC_TOUCH"
  ],
  "providerByClass": [
    [
      "Druid",
      "MARK_OF_THE_WILD"
    ],
    [
      "Warrior",
      "BATTLE_SHOUT"
    ],
    [
      "Mage",
      "ARCANE_INTELLECT"
    ],
    [
      "Shaman",
      "SKYFURY"
    ],
    [
      "Demon Hunter",
      "CHAOS_BRAND"
    ],
    [
      "Monk",
      "MYSTIC_TOUCH"
    ]
  ],
  "offensiveProfiles": {
    "62": {
      "name": "Arcane Mage",
      "gains": {
        "MARK_OF_THE_WILD": 0.02567533048099575,
        "BATTLE_SHOUT": 0,
        "ARCANE_INTELLECT": 0.0000971347407852763,
        "SKYFURY": 0.014507091825198604,
        "CHAOS_BRAND": 0.03109929306880419,
        "MYSTIC_TOUCH": 0
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "63": {
      "name": "Fire Mage",
      "gains": {
        "MARK_OF_THE_WILD": 0.025690816432342257,
        "BATTLE_SHOUT": 0.00029225756537250015,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.012658139321528327,
        "CHAOS_BRAND": 0.029934070822312895,
        "MYSTIC_TOUCH": 0.0009494165804303289
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "64": {
      "name": "Frost Mage",
      "gains": {
        "MARK_OF_THE_WILD": 0.029428905061655006,
        "BATTLE_SHOUT": 0.0000795281228164857,
        "ARCANE_INTELLECT": 0.00023048559482834462,
        "SKYFURY": 0.01726710587970932,
        "CHAOS_BRAND": 0.030312302626020048,
        "MYSTIC_TOUCH": 0.00032915386843148655
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "70": {
      "name": "Retribution Paladin",
      "gains": {
        "MARK_OF_THE_WILD": 0.03046037661403265,
        "BATTLE_SHOUT": 0.04783854558973184,
        "ARCANE_INTELLECT": 0.0006022556919327293,
        "SKYFURY": 0.03378490222038728,
        "CHAOS_BRAND": 0.029368483514402844,
        "MYSTIC_TOUCH": 0.00411020449210695
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "71": {
      "name": "Arms Warrior",
      "gains": {
        "MARK_OF_THE_WILD": 0.028144747542174907,
        "BATTLE_SHOUT": 0.04605339283426857,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.029763347511985838,
        "CHAOS_BRAND": 0,
        "MYSTIC_TOUCH": 0.047952024506877675
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "72": {
      "name": "Fury Warrior",
      "gains": {
        "MARK_OF_THE_WILD": 0.02861603643375967,
        "BATTLE_SHOUT": 0.0454960446548605,
        "ARCANE_INTELLECT": 0.0002027040025985638,
        "SKYFURY": 0.0427703721451135,
        "CHAOS_BRAND": 0.000647960058815622,
        "MYSTIC_TOUCH": 0.04822412619116667
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "102": {
      "name": "Balance Druid",
      "gains": {
        "MARK_OF_THE_WILD": 0.02938306341269894,
        "BATTLE_SHOUT": 0.0001083009118777012,
        "ARCANE_INTELLECT": 0.02972457350583122,
        "SKYFURY": 0.015753469516673113,
        "CHAOS_BRAND": 0.030208021371608516,
        "MYSTIC_TOUCH": 0.0003434817706513105
      },
      "provenance": {
        "source": "archetype_estimate",
        "confidence": "medium",
        "method": "per_buff_archetype_median",
        "donorSpecIds": [
          62,
          63,
          64,
          258,
          262,
          265,
          266,
          267
        ]
      }
    },
    "103": {
      "name": "Feral Druid",
      "gains": {
        "MARK_OF_THE_WILD": 0.02924026931100283,
        "BATTLE_SHOUT": 0.047283287629998096,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.03635196371190632,
        "CHAOS_BRAND": 0.010327859928215121,
        "MYSTIC_TOUCH": 0.01748635438992945
      },
      "provenance": {
        "source": "archetype_estimate",
        "confidence": "medium",
        "method": "per_buff_archetype_median",
        "donorSpecIds": [
          70,
          71,
          72,
          251,
          252,
          255,
          259,
          260,
          261,
          263,
          269,
          577
        ]
      }
    },
    "251": {
      "name": "Frost Death Knight",
      "gains": {
        "MARK_OF_THE_WILD": 0.030374014332037815,
        "BATTLE_SHOUT": 0.04768821014595473,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.05369422545361951,
        "CHAOS_BRAND": 0.027817898814354258,
        "MYSTIC_TOUCH": 0.004739736181558385
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "252": {
      "name": "Unholy Death Knight",
      "gains": {
        "MARK_OF_THE_WILD": 0.02957393256722565,
        "BATTLE_SHOUT": 0.0469729155808718,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.02178909978453425,
        "CHAOS_BRAND": 0.02590770114747172,
        "MYSTIC_TOUCH": 0.0072579367291555116
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "253": {
      "name": "Beast Mastery Hunter",
      "gains": {
        "MARK_OF_THE_WILD": 0.029981801116785122,
        "BATTLE_SHOUT": 0.04883752198866023,
        "ARCANE_INTELLECT": 0.00015057691311102237,
        "SKYFURY": 0.01654737388789167,
        "CHAOS_BRAND": 0.0005739153711302515,
        "MYSTIC_TOUCH": 0.05021529249961518
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "254": {
      "name": "Marksmanship Hunter",
      "gains": {
        "MARK_OF_THE_WILD": 0.028853579177328514,
        "BATTLE_SHOUT": 0.048603417812555616,
        "ARCANE_INTELLECT": 0.00028835981154238247,
        "SKYFURY": 0.014980224689097675,
        "CHAOS_BRAND": 0.013094604598105386,
        "MYSTIC_TOUCH": 0.02776357364530333
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "255": {
      "name": "Survival Hunter",
      "gains": {
        "MARK_OF_THE_WILD": 0.029993884854701402,
        "BATTLE_SHOUT": 0.04759365967912439,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.023477508520796865,
        "CHAOS_BRAND": 0.009428685846493501,
        "MYSTIC_TOUCH": 0.033716557002413515
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "258": {
      "name": "Shadow Priest",
      "gains": {
        "MARK_OF_THE_WILD": 0.02942916390808179,
        "BATTLE_SHOUT": 0,
        "ARCANE_INTELLECT": 0.030086102771136637,
        "SKYFURY": 0.016878411008306983,
        "CHAOS_BRAND": 0.030103740117196985,
        "MYSTIC_TOUCH": 0.00009647672825132679
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "259": {
      "name": "Assassination Rogue",
      "gains": {
        "MARK_OF_THE_WILD": 0.029160867828743255,
        "BATTLE_SHOUT": 0.04436757339872743,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.04758343471385565,
        "CHAOS_BRAND": 0.011227034009936743,
        "MYSTIC_TOUCH": 0.03010911053183265
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "260": {
      "name": "Outlaw Rogue",
      "gains": {
        "MARK_OF_THE_WILD": 0.026138402083082247,
        "BATTLE_SHOUT": 0.046920097069358714,
        "ARCANE_INTELLECT": 0.0016957697303809915,
        "SKYFURY": 0.05339016700523019,
        "CHAOS_BRAND": 0.0033109654160309535,
        "MYSTIC_TOUCH": 0.047202105443967614
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "261": {
      "name": "Subtlety Rogue",
      "gains": {
        "MARK_OF_THE_WILD": 0.027190201007195915,
        "BATTLE_SHOUT": 0.048041735350709436,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.03364640877898166,
        "CHAOS_BRAND": 0.017637895148194183,
        "MYSTIC_TOUCH": 0.020862264396795595
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "262": {
      "name": "Elemental Shaman",
      "gains": {
        "MARK_OF_THE_WILD": 0.02933722176374287,
        "BATTLE_SHOUT": 0.0003464935949951897,
        "ARCANE_INTELLECT": 0.030114701290848877,
        "SKYFURY": 0.017993955951066586,
        "CHAOS_BRAND": 0.03041082117186682,
        "MYSTIC_TOUCH": 0.0003578096728711344
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "263": {
      "name": "Enhancement Shaman",
      "gains": {
        "MARK_OF_THE_WILD": 0.029319670793262406,
        "BATTLE_SHOUT": 0.04779962868861829,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.034701008265689295,
        "CHAOS_BRAND": 0.028474810597152844,
        "MYSTIC_TOUCH": 0.010094357621258121
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "265": {
      "name": "Affliction Warlock",
      "gains": {
        "MARK_OF_THE_WILD": 0.027804695727806018,
        "BATTLE_SHOUT": 0.0003005272956960514,
        "ARCANE_INTELLECT": 0.029472286572256846,
        "SKYFURY": 0.014588648133114647,
        "CHAOS_BRAND": 0.02992645884483669,
        "MYSTIC_TOUCH": 0.0010638296121070034
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "266": {
      "name": "Demonology Warlock",
      "gains": {
        "MARK_OF_THE_WILD": 0.029818003491079992,
        "BATTLE_SHOUT": 0.0001370737009389167,
        "ARCANE_INTELLECT": 0.029976860439405596,
        "SKYFURY": 0.015008776516894563,
        "CHAOS_BRAND": 0.027644651741603,
        "MYSTIC_TOUCH": 0.006388126481687362
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "267": {
      "name": "Destruction Warlock",
      "gains": {
        "MARK_OF_THE_WILD": 0.030064400440419893,
        "BATTLE_SHOUT": 0,
        "ARCANE_INTELLECT": 0.030395612673796004,
        "SKYFURY": 0.016498162516451663,
        "CHAOS_BRAND": 0.030451488383322012,
        "MYSTIC_TOUCH": 0.00014568911208252542
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "269": {
      "name": "Windwalker Monk",
      "gains": {
        "MARK_OF_THE_WILD": 0.02950876695907976,
        "BATTLE_SHOUT": 0.047747016759200095,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.04263897589513839,
        "CHAOS_BRAND": 0.0057275989520884085,
        "MYSTIC_TOUCH": 0.00005528729901664868
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "577": {
      "name": "Havoc Demon Hunter",
      "gains": {
        "MARK_OF_THE_WILD": 0.02832318404458527,
        "BATTLE_SHOUT": 0.04670282962818173,
        "ARCANE_INTELLECT": 0,
        "SKYFURY": 0.038002919158123344,
        "CHAOS_BRAND": 0.000026086065261488034,
        "MYSTIC_TOUCH": 0.014110444383063303
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    },
    "1467": {
      "name": "Devastation Evoker",
      "gains": {
        "MARK_OF_THE_WILD": 0.02938306341269894,
        "BATTLE_SHOUT": 0.0001083009118777012,
        "ARCANE_INTELLECT": 0.02972457350583122,
        "SKYFURY": 0.015753469516673113,
        "CHAOS_BRAND": 0.030208021371608516,
        "MYSTIC_TOUCH": 0.0003434817706513105
      },
      "provenance": {
        "source": "archetype_estimate",
        "confidence": "medium",
        "method": "per_buff_archetype_median",
        "donorSpecIds": [
          62,
          63,
          64,
          258,
          262,
          265,
          266,
          267
        ]
      }
    },
    "1473": {
      "name": "Augmentation Evoker",
      "gains": {
        "MARK_OF_THE_WILD": 0.02938306341269894,
        "BATTLE_SHOUT": 0.0001083009118777012,
        "ARCANE_INTELLECT": 0.02972457350583122,
        "SKYFURY": 0.015753469516673113,
        "CHAOS_BRAND": 0.030208021371608516,
        "MYSTIC_TOUCH": 0.0003434817706513105
      },
      "provenance": {
        "source": "archetype_estimate",
        "confidence": "low",
        "method": "per_buff_archetype_median",
        "donorSpecIds": [
          62,
          63,
          64,
          258,
          262,
          265,
          266,
          267
        ]
      }
    },
    "1480": {
      "name": "Devourer Demon Hunter",
      "gains": {
        "MARK_OF_THE_WILD": 0.0298311680782291,
        "BATTLE_SHOUT": 0.0002594058927210652,
        "ARCANE_INTELLECT": 0.03039293320577805,
        "SKYFURY": 0.018102011970344424,
        "CHAOS_BRAND": 0.00020644172671642198,
        "MYSTIC_TOUCH": 0.00027487278352547053
      },
      "provenance": {
        "source": "simc",
        "confidence": "high",
        "method": "exact_profile"
      }
    }
  },
  "utilityCapabilities": {
    "PERSISTENT_GROUP_DR": {
      "layer": "defensive",
      "tier": "S",
      "stacking": "best_only"
    },
    "PERSISTENT_GROUP_HEALTH": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "best_only"
    },
    "MAJOR_GROUP_DR": {
      "layer": "defensive",
      "tier": "S",
      "stacking": "diminishing"
    },
    "GROUP_DR_MAGIC": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "GROUP_DR_AOE": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "GROUP_HEALTH_CD": {
      "layer": "defensive",
      "tier": "S",
      "stacking": "diminishing"
    },
    "GROUP_MAGIC_ABSORB": {
      "layer": "defensive",
      "tier": "B",
      "stacking": "diminishing"
    },
    "EXTERNAL_DR": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "EXTERNAL_IMMUNITY_PHYSICAL": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "EXTERNAL_IMMUNITY_MAGIC": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "EXTERNAL_ABSORB": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "diminishing"
    },
    "EMERGENCY_SAVE": {
      "layer": "defensive",
      "tier": "B",
      "stacking": "diminishing"
    },
    "ENEMY_DAMAGE_REDUCTION": {
      "layer": "defensive",
      "tier": "A",
      "stacking": "best_only"
    },
    "ATTACK_CAST_SLOW": {
      "layer": "defensive",
      "tier": "B",
      "stacking": "best_only"
    },
    "HEALER_MANA_SUPPORT": {
      "layer": "defensive",
      "tier": "B",
      "stacking": "diminishing"
    },
    "SURVIVAL_CONSUMABLE": {
      "layer": "defensive",
      "tier": "B",
      "stacking": "coverage_once"
    },
    "INTERRUPT": {
      "layer": "secondary",
      "tier": "S",
      "stacking": "diminishing"
    },
    "AOE_INTERRUPT_SILENCE": {
      "layer": "secondary",
      "tier": "S",
      "stacking": "diminishing"
    },
    "AOE_STOP": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "ST_STOP": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "AOE_PULL": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "PULL": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "KNOCKBACK": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "ROOT": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "PURGE_MAGIC": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "SOOTHE_ENRAGE": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "DISPEL_MAGIC": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "DISPEL_CURSE": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "DISPEL_POISON": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "DISPEL_DISEASE": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "DISPEL_BLEED": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "diminishing"
    },
    "MASS_DISPEL": {
      "layer": "secondary",
      "tier": "S",
      "stacking": "diminishing"
    },
    "GROUP_MOBILITY": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "FREEDOM": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "STEALTH_SKIP": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "coverage_once"
    },
    "GATEWAY": {
      "layer": "secondary",
      "tier": "A",
      "stacking": "coverage_once"
    },
    "MIND_SOOTHE": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "coverage_once"
    },
    "SPECIAL_CC": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    },
    "THREAT_TRANSFER": {
      "layer": "secondary",
      "tier": "C",
      "stacking": "diminishing"
    },
    "HEALER_RANGE_MOBILITY": {
      "layer": "secondary",
      "tier": "C",
      "stacking": "diminishing"
    },
    "CC_AMPLIFIER": {
      "layer": "secondary",
      "tier": "C",
      "stacking": "diminishing"
    },
    "FEAR_BREAK_GROUP": {
      "layer": "secondary",
      "tier": "B",
      "stacking": "diminishing"
    }
  },
  "utilityAbilities": [
    {
      "key": "DH_BURN_IT_OUT",
      "name": "Burn It Out",
      "spellId": 1266316,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "DISPEL_DISEASE"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_CHAOS_NOVA",
      "name": "Chaos Nova",
      "spellId": 179057,
      "wowClass": "Demon Hunter",
      "specs": [
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_CONSUME_MAGIC",
      "name": "Consume Magic",
      "spellId": 278326,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "PURGE_MAGIC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_DARKNESS",
      "name": "Darkness",
      "spellId": 196718,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "MAJOR_GROUP_DR"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_DISRUPT",
      "name": "Disrupt",
      "spellId": 183752,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "DH_IMPRISON",
      "name": "Imprison",
      "spellId": 217832,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_SIGIL_CHAINS",
      "name": "Sigil of Chains",
      "spellId": 202138,
      "wowClass": "Demon Hunter",
      "specs": [
        "VENGEANCE"
      ],
      "capabilities": [
        "AOE_PULL"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "DH_SIGIL_MISERY",
      "name": "Sigil of Misery",
      "spellId": 207684,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_SIGIL_SILENCE",
      "name": "Sigil of Silence",
      "spellId": 202137,
      "wowClass": "Demon Hunter",
      "specs": [
        "VENGEANCE"
      ],
      "capabilities": [
        "AOE_INTERRUPT_SILENCE"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_SOUL_CLEANSE",
      "name": "Soul Cleanse",
      "spellId": 1266496,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC",
        "VENGEANCE"
      ],
      "capabilities": [
        "DISPEL_CURSE"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_VOID_NOVA",
      "name": "Void Nova",
      "spellId": 1234195,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DH_WAVE_DEBILITATION",
      "name": "Wave of Debilitation",
      "spellId": 452403,
      "wowClass": "Demon Hunter",
      "specs": [
        "DEVOURER",
        "HAVOC"
      ],
      "capabilities": [
        "ATTACK_CAST_SLOW"
      ],
      "availability": "hero_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_ANTI_MAGIC_ZONE",
      "name": "Anti-Magic Zone",
      "spellId": 51052,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "GROUP_DR_MAGIC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_ASPHYXIATE",
      "name": "Asphyxiate",
      "spellId": 221562,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_BLINDING_SLEET",
      "name": "Blinding Sleet",
      "spellId": 207167,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_CONTROL_UNDEAD",
      "name": "Control Undead",
      "spellId": 111673,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_DEATH_GRIP",
      "name": "Death Grip",
      "spellId": 49576,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "PULL"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "DK_FROSTWYRMS_FURY",
      "name": "Frostwyrm's Fury",
      "spellId": 279302,
      "wowClass": "Death Knight",
      "specs": [
        "FROST"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_GNAW",
      "name": "Gnaw",
      "spellId": 47481,
      "wowClass": "Death Knight",
      "specs": [
        "UNHOLY"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "DK_GOREFIENDS_GRASP",
      "name": "Gorefiend's Grasp",
      "spellId": 108199,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD"
      ],
      "capabilities": [
        "AOE_PULL"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_MIND_FREEZE",
      "name": "Mind Freeze",
      "spellId": 47528,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DK_VESTIGIAL_SHELL",
      "name": "Vestigial Shell",
      "spellId": 454851,
      "wowClass": "Death Knight",
      "specs": [
        "BLOOD",
        "FROST",
        "UNHOLY"
      ],
      "capabilities": [
        "GROUP_MAGIC_ABSORB"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_CYCLONE",
      "name": "Cyclone",
      "spellId": 33786,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_HIBERNATE",
      "name": "Hibernate",
      "spellId": 2637,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_INCAP_ROAR",
      "name": "Incapacitating Roar",
      "spellId": 99,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_INNERVATE",
      "name": "Innervate",
      "spellId": 29166,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "HEALER_MANA_SUPPORT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_IRONBARK",
      "name": "Ironbark",
      "spellId": 102342,
      "wowClass": "Druid",
      "specs": [
        "RESTORATION"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_MASS_ENTANGLEMENT",
      "name": "Mass Entanglement",
      "spellId": 102359,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "ROOT"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_MIGHTY_BASH",
      "name": "Mighty Bash",
      "spellId": 5211,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_NATURES_CURE",
      "name": "Nature's Cure",
      "spellId": 88423,
      "wowClass": "Druid",
      "specs": [
        "RESTORATION"
      ],
      "capabilities": [
        "DISPEL_CURSE",
        "DISPEL_MAGIC",
        "DISPEL_POISON"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "DRUID_REMOVE_CORRUPTION",
      "name": "Remove Corruption",
      "spellId": 440015,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "DISPEL_CURSE",
        "DISPEL_POISON"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_SKULL_BASH",
      "name": "Skull Bash",
      "spellId": 106839,
      "wowClass": "Druid",
      "specs": [
        "FERAL",
        "GUARDIAN"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_SOLAR_BEAM",
      "name": "Solar Beam",
      "spellId": 78675,
      "wowClass": "Druid",
      "specs": [
        "BALANCE"
      ],
      "capabilities": [
        "AOE_INTERRUPT_SILENCE"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_SOOTHE",
      "name": "Soothe",
      "spellId": 2908,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "SOOTHE_ENRAGE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_STAMPEDING_ROAR",
      "name": "Stampeding Roar",
      "spellId": 106898,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_TYPHOON",
      "name": "Typhoon",
      "spellId": 132469,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "KNOCKBACK"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "DRUID_URSOLS_VORTEX",
      "name": "Ursol's Vortex",
      "spellId": 102793,
      "wowClass": "Druid",
      "specs": [
        "BALANCE",
        "FERAL",
        "GUARDIAN",
        "RESTORATION"
      ],
      "capabilities": [
        "PULL",
        "ROOT"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_BLESSING_BRONZE",
      "name": "Blessing of the Bronze",
      "spellId": 364342,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "EVOKER_CAUTERIZING_FLAME",
      "name": "Cauterizing Flame",
      "spellId": 374251,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "DISPEL_BLEED",
        "DISPEL_CURSE",
        "DISPEL_DISEASE",
        "DISPEL_POISON"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_EXPUNGE",
      "name": "Expunge",
      "spellId": 365585,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "DISPEL_POISON"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_LANDSLIDE",
      "name": "Landslide",
      "spellId": 358385,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "ROOT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_NATURALIZE",
      "name": "Naturalize",
      "spellId": 360823,
      "wowClass": "Evoker",
      "specs": [
        "PRESERVATION"
      ],
      "capabilities": [
        "DISPEL_MAGIC",
        "DISPEL_POISON"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "EVOKER_OPPRESSING_ROAR",
      "name": "Oppressing Roar",
      "spellId": 372048,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "CC_AMPLIFIER"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_OVERAWE",
      "name": "Overawe",
      "spellId": 374346,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "SOOTHE_ENRAGE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_QUELL",
      "name": "Quell",
      "spellId": 351338,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "spec_access",
      "availabilityFactor": 1000
    },
    {
      "key": "EVOKER_RESCUE",
      "name": "Rescue",
      "spellId": 370665,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "FREEDOM"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_SLEEP_WALK",
      "name": "Sleep Walk",
      "spellId": 360806,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_SOURCE_MAGIC",
      "name": "Source of Magic",
      "spellId": 369459,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "HEALER_MANA_SUPPORT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_SPATIAL_PARADOX",
      "name": "Spatial Paradox",
      "spellId": 406732,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "HEALER_RANGE_MOBILITY"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_TAIL_SWIPE",
      "name": "Tail Swipe",
      "spellId": 368970,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "racial",
      "availabilityFactor": 1000
    },
    {
      "key": "EVOKER_TIME_DILATION",
      "name": "Time Dilation",
      "spellId": 357170,
      "wowClass": "Evoker",
      "specs": [
        "PRESERVATION"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_TIME_SPIRAL",
      "name": "Time Spiral",
      "spellId": 374968,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "EVOKER_WING_BUFFET",
      "name": "Wing Buffet",
      "spellId": null,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "KNOCKBACK"
      ],
      "availability": "racial",
      "availabilityFactor": 1000
    },
    {
      "key": "EVOKER_ZEPHYR",
      "name": "Zephyr",
      "spellId": 374227,
      "wowClass": "Evoker",
      "specs": [
        "AUGMENTATION",
        "DEVASTATION",
        "PRESERVATION"
      ],
      "capabilities": [
        "GROUP_DR_AOE",
        "GROUP_MOBILITY"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_BINDING_SHOT",
      "name": "Binding Shot",
      "spellId": 109248,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_COUNTER_SHOT",
      "name": "Counter Shot",
      "spellId": 147362,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_FREEZING_TRAP",
      "name": "Freezing Trap",
      "spellId": 187650,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "HUNTER_INTIMIDATION",
      "name": "Intimidation",
      "spellId": 19577,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_MASTERS_CALL",
      "name": "Master's Call",
      "spellId": 53271,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "FREEDOM"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_MISDIRECTION",
      "name": "Misdirection",
      "spellId": 34477,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "THREAT_TRANSFER"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_MUZZLE",
      "name": "Muzzle",
      "spellId": 187707,
      "wowClass": "Hunter",
      "specs": [
        "SURVIVAL"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_ROAR_SACRIFICE",
      "name": "Roar of Sacrifice",
      "spellId": 53480,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_SCARE_BEAST",
      "name": "Scare Beast",
      "spellId": 1513,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "HUNTER_TRANQ_SHOT",
      "name": "Tranquilizing Shot",
      "spellId": 19801,
      "wowClass": "Hunter",
      "specs": [
        "BEAST_MASTERY",
        "MARKSMANSHIP",
        "SURVIVAL"
      ],
      "capabilities": [
        "PURGE_MAGIC",
        "SOOTHE_ENRAGE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_COUNTERSPELL",
      "name": "Counterspell",
      "spellId": 2139,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "MAGE_DRAGONS_BREATH",
      "name": "Dragon's Breath",
      "spellId": 31661,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_FROST_NOVA",
      "name": "Frost Nova",
      "spellId": 122,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "ROOT"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "MAGE_MASS_INVIS",
      "name": "Mass Invisibility",
      "spellId": 414664,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "STEALTH_SKIP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_POLYMORPH",
      "name": "Polymorph",
      "spellId": null,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "MAGE_REMOVE_CURSE",
      "name": "Remove Curse",
      "spellId": 475,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "DISPEL_CURSE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_RING_OF_FROST",
      "name": "Ring of Frost",
      "spellId": 113724,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_SPELLSTEAL",
      "name": "Spellsteal",
      "spellId": 30449,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "PURGE_MAGIC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MAGE_SUPERNOVA",
      "name": "Supernova",
      "spellId": 157980,
      "wowClass": "Mage",
      "specs": [
        "ARCANE",
        "FIRE",
        "FROST"
      ],
      "capabilities": [
        "AOE_STOP",
        "KNOCKBACK"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_DETOX_BREW_WW",
      "name": "Detox",
      "spellId": 115450,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "WINDWALKER"
      ],
      "capabilities": [
        "DISPEL_DISEASE",
        "DISPEL_POISON"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_DETOX_MW",
      "name": "Detox",
      "spellId": 115450,
      "wowClass": "Monk",
      "specs": [
        "MISTWEAVER"
      ],
      "capabilities": [
        "DISPEL_DISEASE",
        "DISPEL_MAGIC",
        "DISPEL_POISON"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "MONK_LEG_SWEEP",
      "name": "Leg Sweep",
      "spellId": 119381,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "MONK_LIFE_COCOON",
      "name": "Life Cocoon",
      "spellId": 116849,
      "wowClass": "Monk",
      "specs": [
        "MISTWEAVER"
      ],
      "capabilities": [
        "EXTERNAL_ABSORB"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_PARALYSIS",
      "name": "Paralysis",
      "spellId": 115078,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_PRESSURE_POINTS",
      "name": "Pressure Points",
      "spellId": 450432,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "SOOTHE_ENRAGE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_RESTORAL",
      "name": "Restoral",
      "spellId": 388615,
      "wowClass": "Monk",
      "specs": [
        "MISTWEAVER"
      ],
      "capabilities": [
        "MASS_DISPEL"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_REVIVAL",
      "name": "Revival",
      "spellId": 115310,
      "wowClass": "Monk",
      "specs": [
        "MISTWEAVER"
      ],
      "capabilities": [
        "MASS_DISPEL"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_RING_PEACE",
      "name": "Ring of Peace",
      "spellId": 116844,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "AOE_STOP",
        "KNOCKBACK"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_SPEAR_HAND",
      "name": "Spear Hand Strike",
      "spellId": 116705,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "WINDWALKER"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_TIGERS_LUST",
      "name": "Tiger's Lust",
      "spellId": 116841,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "FREEDOM"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "MONK_WINDWALKING",
      "name": "Windwalking",
      "spellId": 157411,
      "wowClass": "Monk",
      "specs": [
        "BREWMASTER",
        "MISTWEAVER",
        "WINDWALKER"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_AURA_MASTERY",
      "name": "Aura Mastery",
      "spellId": 31821,
      "wowClass": "Paladin",
      "specs": [
        "HOLY"
      ],
      "capabilities": [
        "MAJOR_GROUP_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_AVENGERS_SHIELD",
      "name": "Avenger's Shield",
      "spellId": 31935,
      "wowClass": "Paladin",
      "specs": [
        "PROTECTION"
      ],
      "capabilities": [
        "AOE_INTERRUPT_SILENCE"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "PALADIN_BLINDING_LIGHT",
      "name": "Blinding Light",
      "spellId": 115750,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_BOP",
      "name": "Blessing of Protection",
      "spellId": 1022,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "EXTERNAL_IMMUNITY_PHYSICAL"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_CLEANSE",
      "name": "Cleanse",
      "spellId": 4987,
      "wowClass": "Paladin",
      "specs": [
        "HOLY"
      ],
      "capabilities": [
        "DISPEL_DISEASE",
        "DISPEL_MAGIC",
        "DISPEL_POISON"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "PALADIN_CLEANSE_TOXINS",
      "name": "Cleanse Toxins",
      "spellId": 440013,
      "wowClass": "Paladin",
      "specs": [
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "DISPEL_DISEASE",
        "DISPEL_POISON"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_DEVOTION_AURA",
      "name": "Devotion Aura",
      "spellId": null,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "PERSISTENT_GROUP_DR"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "PALADIN_FREEDOM",
      "name": "Blessing of Freedom",
      "spellId": 1044,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "FREEDOM"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_HOJ",
      "name": "Hammer of Justice",
      "spellId": 853,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "PALADIN_LAY_ON_HANDS",
      "name": "Lay on Hands",
      "spellId": 633,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "EMERGENCY_SAVE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_REBUKE",
      "name": "Rebuke",
      "spellId": 96231,
      "wowClass": "Paladin",
      "specs": [
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_SAC",
      "name": "Blessing of Sacrifice",
      "spellId": 6940,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_SPELLWARDING",
      "name": "Blessing of Spellwarding",
      "spellId": 204018,
      "wowClass": "Paladin",
      "specs": [
        "PROTECTION"
      ],
      "capabilities": [
        "EXTERNAL_IMMUNITY_MAGIC"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PALADIN_TURN_EVIL",
      "name": "Turn Evil",
      "spellId": 10326,
      "wowClass": "Paladin",
      "specs": [
        "HOLY",
        "PROTECTION",
        "RETRIBUTION"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_BARRIER",
      "name": "Power Word: Barrier",
      "spellId": 62618,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE"
      ],
      "capabilities": [
        "MAJOR_GROUP_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_DISPEL_MAGIC",
      "name": "Dispel Magic",
      "spellId": 528,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "PURGE_MAGIC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_DOMINATE_MIND",
      "name": "Dominate Mind",
      "spellId": 205364,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_FORTITUDE",
      "name": "Power Word: Fortitude",
      "spellId": 21562,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "PERSISTENT_GROUP_HEALTH"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "PRIEST_GUARDIAN_SPIRIT",
      "name": "Guardian Spirit",
      "spellId": 47788,
      "wowClass": "Priest",
      "specs": [
        "HOLY"
      ],
      "capabilities": [
        "EMERGENCY_SAVE"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_LEAP_FAITH",
      "name": "Leap of Faith",
      "spellId": 73325,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "FREEDOM"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_MASS_DISPEL",
      "name": "Mass Dispel",
      "spellId": 32375,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "MASS_DISPEL"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_MIND_SOOTHE",
      "name": "Mind Soothe",
      "spellId": 453,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "MIND_SOOTHE"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "PRIEST_PAIN_SUPP",
      "name": "Pain Suppression",
      "spellId": 33206,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_PSYCHIC_SCREAM",
      "name": "Psychic Scream",
      "spellId": 8122,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_PURIFY",
      "name": "Purify",
      "spellId": 527,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY"
      ],
      "capabilities": [
        "DISPEL_DISEASE",
        "DISPEL_MAGIC"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "PRIEST_PURIFY_DISEASE",
      "name": "Purify Disease",
      "spellId": 440006,
      "wowClass": "Priest",
      "specs": [
        "SHADOW"
      ],
      "capabilities": [
        "DISPEL_DISEASE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_SHACKLE_HORROR",
      "name": "Shackle Horror",
      "spellId": 9484,
      "wowClass": "Priest",
      "specs": [
        "DISCIPLINE",
        "HOLY",
        "SHADOW"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "PRIEST_SILENCE",
      "name": "Silence",
      "spellId": 15487,
      "wowClass": "Priest",
      "specs": [
        "SHADOW"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "PRIEST_VAMPIRIC_EMBRACE",
      "name": "Vampiric Embrace",
      "spellId": 15286,
      "wowClass": "Priest",
      "specs": [
        "SHADOW"
      ],
      "capabilities": [
        "EMERGENCY_SAVE"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_ATROPHIC",
      "name": "Atrophic Poison",
      "spellId": 381637,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "ENEMY_DAMAGE_REDUCTION"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "ROGUE_BLIND",
      "name": "Blind",
      "spellId": 2094,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "ROGUE_DISTRACT",
      "name": "Distract",
      "spellId": 1725,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "STEALTH_SKIP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_GOUGE",
      "name": "Gouge",
      "spellId": 1776,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "ROGUE_KICK",
      "name": "Kick",
      "spellId": 1766,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_KIDNEY",
      "name": "Kidney Shot",
      "spellId": 408,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_NUMBING",
      "name": "Numbing Poison",
      "spellId": 5761,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "ATTACK_CAST_SLOW"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "ROGUE_SAP",
      "name": "Sap",
      "spellId": 6770,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_SHIV",
      "name": "Shiv",
      "spellId": 5938,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "SOOTHE_ENRAGE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "ROGUE_SHROUD",
      "name": "Shroud of Concealment",
      "spellId": 114018,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "STEALTH_SKIP"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "ROGUE_TRICKS",
      "name": "Tricks of the Trade",
      "spellId": 57934,
      "wowClass": "Rogue",
      "specs": [
        "ASSASSINATION",
        "OUTLAW",
        "SUBTLETY"
      ],
      "capabilities": [
        "THREAT_TRANSFER"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_CAP_TOTEM",
      "name": "Capacitor Totem",
      "spellId": 192058,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_CLEANSE_SPIRIT",
      "name": "Cleanse Spirit",
      "spellId": 440012,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT"
      ],
      "capabilities": [
        "DISPEL_CURSE"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_EARTHGRAB",
      "name": "Earthgrab Totem",
      "spellId": 51485,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "ROOT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_HEX",
      "name": "Hex",
      "spellId": 51514,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_POISON_TOTEM",
      "name": "Poison Cleansing Totem",
      "spellId": 383013,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "DISPEL_POISON"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_PURGE",
      "name": "Purge",
      "spellId": 370,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "PURGE_MAGIC"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_PURIFY_SPIRIT",
      "name": "Purify Spirit",
      "spellId": 77130,
      "wowClass": "Shaman",
      "specs": [
        "RESTORATION"
      ],
      "capabilities": [
        "DISPEL_CURSE",
        "DISPEL_MAGIC"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "SHAMAN_SPIRIT_LINK",
      "name": "Spirit Link Totem",
      "spellId": 98008,
      "wowClass": "Shaman",
      "specs": [
        "RESTORATION"
      ],
      "capabilities": [
        "MAJOR_GROUP_DR"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_SUNDERING",
      "name": "Sundering",
      "spellId": 197214,
      "wowClass": "Shaman",
      "specs": [
        "ENHANCEMENT"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_THUNDERSTORM",
      "name": "Thunderstorm",
      "spellId": 51490,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL"
      ],
      "capabilities": [
        "KNOCKBACK"
      ],
      "availability": "spec_only",
      "availabilityFactor": 1000
    },
    {
      "key": "SHAMAN_TREMOR",
      "name": "Tremor Totem",
      "spellId": 8143,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "FEAR_BREAK_GROUP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_WIND_RUSH",
      "name": "Wind Rush Totem",
      "spellId": 192077,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT",
        "RESTORATION"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_WIND_SHEAR_DPS",
      "name": "Wind Shear",
      "spellId": 57994,
      "wowClass": "Shaman",
      "specs": [
        "ELEMENTAL",
        "ENHANCEMENT"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "SHAMAN_WIND_SHEAR_RESTO",
      "name": "Wind Shear",
      "spellId": 57994,
      "wowClass": "Shaman",
      "specs": [
        "RESTORATION"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_AXE_TOSS",
      "name": "Axe Toss",
      "spellId": 89766,
      "wowClass": "Warlock",
      "specs": [
        "DEMONOLOGY"
      ],
      "capabilities": [
        "INTERRUPT",
        "ST_STOP"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_BANISH",
      "name": "Banish",
      "spellId": 710,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "SPECIAL_CC"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_CURSE_TONGUES",
      "name": "Curse of Tongues",
      "spellId": 1714,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "ATTACK_CAST_SLOW"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_CURSE_WEAKNESS",
      "name": "Curse of Weakness",
      "spellId": 702,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "ATTACK_CAST_SLOW"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "WARLOCK_DEVOUR_MAGIC",
      "name": "Devour Magic",
      "spellId": 19505,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "PURGE_MAGIC"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_GATEWAY",
      "name": "Demonic Gateway",
      "spellId": 111771,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "GATEWAY"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_HEALTHSTONE",
      "name": "Create Healthstone",
      "spellId": 6201,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "SURVIVAL_CONSUMABLE"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "WARLOCK_HOWL_TERROR",
      "name": "Howl of Terror",
      "spellId": 5484,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_MORTAL_COIL",
      "name": "Mortal Coil",
      "spellId": 6789,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_SHADOWFURY",
      "name": "Shadowfury",
      "spellId": 30283,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_SINGE_MAGIC",
      "name": "Singe Magic",
      "spellId": 89808,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "DISPEL_MAGIC"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "WARLOCK_SPELL_LOCK",
      "name": "Spell Lock",
      "spellId": 19647,
      "wowClass": "Warlock",
      "specs": [
        "AFFLICTION",
        "DEMONOLOGY",
        "DESTRUCTION"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "pet_conditional",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_BERSERKER_SHOUT",
      "name": "Berserker Shout",
      "spellId": 384100,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "FEAR_BREAK_GROUP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_CHAMPIONS_SPEAR",
      "name": "Champion's Spear",
      "spellId": 376079,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "AOE_PULL"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_DISRUPTING_SHOUT",
      "name": "Disrupting Shout",
      "spellId": 386071,
      "wowClass": "Warrior",
      "specs": [
        "PROTECTION"
      ],
      "capabilities": [
        "AOE_INTERRUPT_SILENCE"
      ],
      "availability": "spec_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_INTERVENE",
      "name": "Intervene",
      "spellId": 3411,
      "wowClass": "Warrior",
      "specs": [
        "PROTECTION"
      ],
      "capabilities": [
        "EXTERNAL_DR"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_INTIMIDATING_SHOUT",
      "name": "Intimidating Shout",
      "spellId": 5246,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_PIERCING_HOWL",
      "name": "Piercing Howl",
      "spellId": 12323,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "GROUP_MOBILITY"
      ],
      "availability": "choice_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_PUMMEL",
      "name": "Pummel",
      "spellId": 6552,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "INTERRUPT"
      ],
      "availability": "baseline",
      "availabilityFactor": 1000
    },
    {
      "key": "WARRIOR_RALLY",
      "name": "Rallying Cry",
      "spellId": 97462,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "GROUP_HEALTH_CD"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_SHOCKWAVE",
      "name": "Shockwave",
      "spellId": 46968,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "AOE_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    },
    {
      "key": "WARRIOR_STORM_BOLT",
      "name": "Storm Bolt",
      "spellId": 107570,
      "wowClass": "Warrior",
      "specs": [
        "ARMS",
        "FURY",
        "PROTECTION"
      ],
      "capabilities": [
        "ST_STOP"
      ],
      "availability": "class_talent",
      "availabilityFactor": 500
    }
  ],
  "dungeonRelevanceByMapId": {
    "249": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 2,
      "AOE_STOP": 3,
      "ATTACK_CAST_SLOW": 3,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 2,
      "DISPEL_CURSE": 3,
      "DISPEL_DISEASE": 2,
      "DISPEL_MAGIC": 3,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 2,
      "EXTERNAL_IMMUNITY_PHYSICAL": 3,
      "FEAR_BREAK_GROUP": 3,
      "FREEDOM": 3,
      "GATEWAY": 0,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 2,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 1,
      "MASS_DISPEL": 3,
      "MIND_SOOTHE": 0,
      "PULL": 2,
      "PURGE_MAGIC": 3,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 3,
      "SPECIAL_CC": 3,
      "ST_STOP": 3,
      "STEALTH_SKIP": 0,
      "THREAT_TRANSFER": 1
    },
    "250": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 2,
      "AOE_STOP": 3,
      "ATTACK_CAST_SLOW": 3,
      "CC_AMPLIFIER": 3,
      "DISPEL_BLEED": 1,
      "DISPEL_CURSE": 2,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 2,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 3,
      "EXTERNAL_IMMUNITY_PHYSICAL": 2,
      "FEAR_BREAK_GROUP": 0,
      "FREEDOM": 1,
      "GATEWAY": 0,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 2,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 3,
      "MASS_DISPEL": 1,
      "MIND_SOOTHE": 1,
      "PULL": 2,
      "PURGE_MAGIC": 2,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 0,
      "SPECIAL_CC": 3,
      "ST_STOP": 3,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "399": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 1,
      "AOE_STOP": 2,
      "ATTACK_CAST_SLOW": 2,
      "CC_AMPLIFIER": 1,
      "DISPEL_BLEED": 0,
      "DISPEL_CURSE": 0,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 3,
      "DISPEL_POISON": 0,
      "EXTERNAL_IMMUNITY_MAGIC": 3,
      "EXTERNAL_IMMUNITY_PHYSICAL": 1,
      "FEAR_BREAK_GROUP": 0,
      "FREEDOM": 2,
      "GATEWAY": 1,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 3,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 2,
      "INTERRUPT": 3,
      "KNOCKBACK": 1,
      "MASS_DISPEL": 3,
      "MIND_SOOTHE": 2,
      "PULL": 1,
      "PURGE_MAGIC": 3,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 0,
      "SPECIAL_CC": 1,
      "ST_STOP": 2,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "584": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 1,
      "AOE_STOP": 2,
      "ATTACK_CAST_SLOW": 2,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 3,
      "DISPEL_CURSE": 0,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 3,
      "DISPEL_POISON": 2,
      "EXTERNAL_IMMUNITY_MAGIC": 2,
      "EXTERNAL_IMMUNITY_PHYSICAL": 3,
      "FEAR_BREAK_GROUP": 0,
      "FREEDOM": 3,
      "GATEWAY": 1,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 3,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 2,
      "MASS_DISPEL": 3,
      "MIND_SOOTHE": 1,
      "PULL": 1,
      "PURGE_MAGIC": 0,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 0,
      "SPECIAL_CC": 1,
      "ST_STOP": 2,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "585": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 2,
      "AOE_STOP": 2,
      "ATTACK_CAST_SLOW": 3,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 0,
      "DISPEL_CURSE": 0,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 2,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 3,
      "EXTERNAL_IMMUNITY_PHYSICAL": 1,
      "FEAR_BREAK_GROUP": 2,
      "FREEDOM": 1,
      "GATEWAY": 2,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 3,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 2,
      "MASS_DISPEL": 1,
      "MIND_SOOTHE": 0,
      "PULL": 2,
      "PURGE_MAGIC": 1,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 2,
      "SPECIAL_CC": 2,
      "ST_STOP": 2,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "586": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 1,
      "AOE_STOP": 3,
      "ATTACK_CAST_SLOW": 3,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 1,
      "DISPEL_CURSE": 3,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 3,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 2,
      "EXTERNAL_IMMUNITY_PHYSICAL": 2,
      "FEAR_BREAK_GROUP": 0,
      "FREEDOM": 3,
      "GATEWAY": 3,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 2,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 1,
      "MASS_DISPEL": 3,
      "MIND_SOOTHE": 1,
      "PULL": 1,
      "PURGE_MAGIC": 3,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 3,
      "SPECIAL_CC": 1,
      "ST_STOP": 3,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "587": {
      "AOE_INTERRUPT_SILENCE": 3,
      "AOE_PULL": 2,
      "AOE_STOP": 3,
      "ATTACK_CAST_SLOW": 3,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 2,
      "DISPEL_CURSE": 3,
      "DISPEL_DISEASE": 0,
      "DISPEL_MAGIC": 3,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 2,
      "EXTERNAL_IMMUNITY_PHYSICAL": 2,
      "FEAR_BREAK_GROUP": 2,
      "FREEDOM": 1,
      "GATEWAY": 1,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 3,
      "GROUP_MAGIC_ABSORB": 3,
      "GROUP_MOBILITY": 2,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 2,
      "MASS_DISPEL": 3,
      "MIND_SOOTHE": 2,
      "PULL": 2,
      "PURGE_MAGIC": 2,
      "ROOT": 1,
      "SOOTHE_ENRAGE": 3,
      "SPECIAL_CC": 3,
      "ST_STOP": 3,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    },
    "588": {
      "AOE_INTERRUPT_SILENCE": 2,
      "AOE_PULL": 1,
      "AOE_STOP": 3,
      "ATTACK_CAST_SLOW": 1,
      "CC_AMPLIFIER": 2,
      "DISPEL_BLEED": 2,
      "DISPEL_CURSE": 0,
      "DISPEL_DISEASE": 1,
      "DISPEL_MAGIC": 2,
      "DISPEL_POISON": 3,
      "EXTERNAL_IMMUNITY_MAGIC": 2,
      "EXTERNAL_IMMUNITY_PHYSICAL": 2,
      "FEAR_BREAK_GROUP": 0,
      "FREEDOM": 1,
      "GATEWAY": 1,
      "GROUP_DR_AOE": 3,
      "GROUP_DR_MAGIC": 2,
      "GROUP_MAGIC_ABSORB": 2,
      "GROUP_MOBILITY": 3,
      "HEALER_MANA_SUPPORT": 1,
      "HEALER_RANGE_MOBILITY": 1,
      "INTERRUPT": 3,
      "KNOCKBACK": 2,
      "MASS_DISPEL": 2,
      "MIND_SOOTHE": 1,
      "PULL": 1,
      "PURGE_MAGIC": 1,
      "ROOT": 2,
      "SOOTHE_ENRAGE": 2,
      "SPECIAL_CC": 1,
      "ST_STOP": 3,
      "STEALTH_SKIP": 1,
      "THREAT_TRANSFER": 1
    }
  }
} as const
